### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by TheSuperN3rd** [isotope-engineering/PiMod-Zero#4]
Ok, so I finished soldering everything and I tested the connections to my TV, but the screen is black and white instead of color on my color tv, and after the 'Welcome to Raspbian' screen, it just stays blank. I can VNC into the pi zero and the desktop shows up remotely on my laptop, but not on the television. Is there something wrong with the physical connections? Or is it software related? I'd appreciate any feedback

**Comment by TheSuperN3rd** [comment]
Another thing that just happened, I went to fine tune the inductor and the interior threaded piece shattered as I very gently turned it with a flathead screwdriver. Would there be any way to get a replacement inductor part to resolder to the pHAT?

**Comment by azzeloof** [comment]
Are there any other displays plugged in? If an HDMI display is connected on boot it can disable composite output. You can take a look at the settings in raspi-config as well to see what the output mode is set to.
As for the B&W/color, are you using an NTSC TV? If its PAL, that could be an issue. Another possible cause is that the tuning inductor is not set properly. Which brings us to the last point- the inductor is a [Coilcraft 7M3-183](https://www.coilcraft.com/en-us/products/rf/tunable-rf-inductors/vertical-mount/slot7/7m3-183/). You can grab a replacement form their website, or you may be able to email/call and just ask for a replacement core, which can be fully unscrewed and replaced. The "set" position is usually when the top of the core protrudes ~1/8"

**Comment by TheSuperN3rd** [comment]
Nope, I just have the one coax cable going from the Pi to the TV. The TV is an NTSC Hitachi color TV, I've used it for RF broadcasting before until my blonder tongue died. The weird thing is I get a picture at startup but then the desktop doesn't display on screen, but I can VNC into it on my laptop and see it just fine.

 Thanks for the info on the inductor, I'll see about ordering a replacement or email about a replacement core. The inductor was screwed all the way in and when I went to unscrew the core it just shattered :/ I'll attach am image ir a link to an image in a little bit

**Comment by azzeloof** [comment]
Hmm, the lack of color is weird. Like I said it may be fixed by tuning the inductor- can you turn it by hand, or is the broken part fully in the thread?
Also, if there's nothing in the video output settings of raspi-config, you could try and add this to your pi's config.txt:
`enable_tvout=1`

**Comment by TheSuperN3rd** [comment]
Ok, partial success! I now have color output! I think when the core shattered i site the inductor, there was a small piece lodged inside interfering with the signal. After completely unscrewing the core, the display changed to color, and stayed that way after partially reinserting the core so I didn't lose it. 

With that fixed, I'm going to work on the software end of things to see if I can get a full display, rather than just the welcome splash screen.

**Comment by TheSuperN3rd** [comment]
Video success! The problem was the AMD Freesync throwing the video detection off. I changed the driver from 'kms' to fkms' in the config.txt
dtoverlay=vc4-fkms-v3d

I'm still having trouble with audio, for some reason I still can't run the script even under the root with the 'sudo su' command. I've tried 'sudo PiMod-Audio-Setup.sh' and './PiMod-Audio-Setup.sh' to no avail. I can't figure out for the life of me how to run the script, even though I', in the directory folder of the cloned repository!

**Comment by azzeloof** [comment]
Great! Nice work, that's a fantastic find. I would not have suspected Freesync, but I'm glad you were able to work out a solution.
Have you tried making the script executable? `chmod +x PiMod-Audio-Setup.sh`
If that doesn't work, the getting started guide lists the commands that the script automates, you could run them manually (there are only a couple)

**Comment by TheSuperN3rd** [comment]
Total success!! Audio and Video functions well! 
I believe the command that ran the shell was 'sudo sh PiMod-Audio-Setup.sh" after making it executable with the chmod command.

**Comment by azzeloof** [comment]
Great work! Thanks for reporting back & following up.
