### ISSUE TITLE
No video out

### ISSUE THREAD

**Issue by haxorthematrix** [isotope-engineering/PiMod-Zero#6]
I just received my PiMod-Zero a few days ago, and I'm having some issues, specifically, I see no desktop or video out but sound works just fine.  Fresh Raspberry Pi OS with desktop install (Kernel version: 5.15 Debian version: 11 (bullseye)) on a Raspberry Pi Zero W 1.1.  config.txt is attached - I've manually added the two required lines in the setup documentation, as well as verifying  with raspi-config that composite output is enabled and even added `enable_tvout=1` as well.  I also bounced back and forth between `dtoverlay=vc4-fkms-v3d` and `dtoverlay=vc4-kms-v3d` and no change was observed.  Yes, a reboot/power off was performed between each change.  No HDMI was connected during testing.

I've tested on two different TVs, one known to be working (the other unknown), through a 75ohm (coax) to 300ohm (dual lead) adapter.  Sound works, but no video on either channel 2 or 3, but I'm unsure how to switch on the PiMod-Zero if needed.

Changed to a Raspberry Pi 2 model B v1.1, to same effect.  I may not have changed all of the config.txt output there, as it was early on in my testing.

Figuring that my 75-300ohm adapter may be bad, I switched to a known working TV that could take direct coax input.  The TV could sense that there was some signal on channel 2 (but not 3), audio played, but still no video/desktop shown on the TV.

Any help here is appreciated.  I'm assuming J2 is for switching between channel 2 and 3, so I will populate that today and see if there are any changes.

[config.txt](https://github.com/isotope-engineering/PiMod-Zero/files/9665594/config.txt)

**Comment by haxorthematrix** [comment]
....and the biggest Facepalm moment of them all:

If you want composite video to work, one needs to populate JP2 and the unpopulated TV header on the Pi Zero.

I did that and it works!  Happy to do a pull request to make the instructions more clear if you think it is warranted.

**Comment by azzeloof** [comment]
I'm glad you were able to get it working! I just made a slight change to [the instructions](https://github.com/isotope-engineering/PiMod-Zero/tree/master/setup) that I hope makes the issue more clear, but if you've got any further suggestions I'd love to hear them!
